name: PingFFA
version: '1.0.0'
main: lol.ysmu.ffa.Main
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - FastAsyncWorldEdit
  - XyrisKits
authors:
  - ysmu
description: Made for PingPvP

commands:
  ffa:
    description: Main admin command for FFA.
    permission: ffa.admin
    usage: /ffa
  leaderboard:
    description: View the top player rankings.
    usage: /leaderboard
  spawn:
    description: Teleport to the server spawn.
    usage: /spawn
  setspawn:
    description: Set the server spawn location.
    usage: /setspawn
    permission: ffa.admin
  suicide:
    permission: ffa.commands.suicide
    aliases: [kms, iwanttodie, killme]
  broadcast:
    permission: ffa.commands.broadcast
  rules:
    description: View the server rules.
  sit:
    permission: ffa.commands.sit
  stats:
    description: View your player statistics.
  heal:
    permission: ffa.commands.heal
  message:
    aliases: [msg, w, tell]
  reply:
    aliases: [r]
  fly:
    permission: ffa.commands.fly
  ping:
    description: Check your latency.
  nickname:
    permission: ffa.commands.nickname
    aliases: [nick]
  settings:
    description: Open the settings menu.
  coolarena:
    permission: ffa.coolarena.use
    aliases: [ca]
  toggleautogg:
    permission: ffa.settings.toggleautogg
  toggleprivacymode:
    permission: ffa.settings.toggleprivacymode
  togglementionsound:
    permission: ffa.settings.togglementionsound
  toggleprivatemessages:
    permission: ffa.settings.toggleprivatemessages
  togglequickrespawn:
    permission: ffa.settings.togglequickrespawn

permissions:
  ffa.admin:
    default: op
  ffa.commands.suicide:
    default: true
  ffa.commands.broadcast:
    default: op
  ffa.commands.sit:
    default: true
  ffa.commands.heal:
    default: op
  ffa.commands.fly:
    default: op
  ffa.commands.nickname:
    default: true
  ffa.coolarena.use:
    default: true